services:
  - type: web
    name: telegram-summary-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        value: AndroidAndAI
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
